### ISSUE TITLE
Incorrect result for second largest number when duplicates present in list

### ISSUE THREAD

**Issue by Shrreya** [shivangisinghal/Learn-IT-Girl-Practice-Exercises#3]
In the task to find second largest number in the list, if the list contains duplicate items the code returns incorrect result.
For example, if the list is : 2 3 6 6 5
The second largest number is 5. However, the result obtained is 6.
Can you fix this?

**Comment by shivangisinghal** [comment]
Exercise 2 is working fine now. You too check it once [Shrreya](https://github.com/Shrreya). Check Exercise 3 also.

**Comment by Shrreya** [comment]
Checked. Both work fine. Good job! :)
